server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: team-service

management:
  security:
    enabled: false

logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG